spring.application.name=smartdesk

# H2 Database
spring.datasource.url=jdbc:h2:mem:smartdeskdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 Console (browser pe database dekh sako)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Secret
jwt.secret=smartdesk-super-secret-key-2024-karan-aawla
jwt.expiration=86400000